import { cookies } from "next/headers";
import { Montserrat, Inter } from "next/font/google";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import NavbarCustom from "@/components/shared/NavbarCustom";
import "../styles/App.scss";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400"],
  variable: "--font-inter",
});
const fmon = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

const colorsVariable = {
  "--main-color": "#0B1D50",
  "--yellow-color": "#FFD700",
};

// seo
export const metadata = {
  title: "title global",
  description: "Generated by create next app",
  icons: {
    icon: "/next.svg",
  },
  robots: {
    index: false,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({ children }) {
  // const cookiesData = cookies().get("OutSiteJWT");
  // console.log(cookies().get("OutSiteJWT"), "cookies().getAll()");
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body
          className={`${inter.variable} ${fmon.variable}`}
          style={colorsVariable}
        >
          <NavbarCustom />
          {children}
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
